kind: Secret
apiVersion: v1
metadata:
  name: rmq-cluster-secret
stringData:
  cookie: ERLANG_COOKIE
  password: admin123
  url: amqp://RABBITMQ_USER:RABBITMQ_PASS@rmq-cluster-balancer
  username: admin
type: Opaque
