kind: Service
apiVersion: v1
metadata:
  labels:
    app: rmq-cluster
  name: rmq-cluster
spec:
  type: ClusterIP
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: stomp
    targetPort: 61613
    port: 61613
  selector:
    app: rmq-cluster
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: rmq-cluster-web
  name: rmq-cluster-web
spec:
  type: NodePort
  ports:
    - name: web
      port: 15672
      targetPort: 15672
      nodePort: 32672
  selector:
    app: rmq-cluster
